#21 - Unit & Func tests improvements
b2p-ayman/sandbox pull request #22
Opened 2021-08-26 11:23 UTC by b2p-ayman

Closes #21

2021-08-26 12:21 UTC, b2p-fred reviewed
Quelques remarques ;)

2021-08-26 12:21 UTC, b2p-fred commented on tests/Func/Entity/AbstractEndPoint.php
> +abstract class AbstractEndPoint extends WebTestCase
Tu es sûr que c'est vraiment utile ?
Si c'est utile, il ne faut pas mettre ce fichier dans ce répertoire mais dans un répertoire Utils. Voir le répertoire Base dans mon dépôt ...

2021-08-26 12:21 UTC, b2p-fred commented on tests/Func/Entity/FileTest.php
> +        self::assertEquals(Response::HTTP_OK, $response->getStatusCode());
Tu peux utiliser assertResponseIsSuccesfull

2021-08-26 12:21 UTC, b2p-fred commented on tests/Func/Entity/UserTest.php
> +    private $userPayload = '{"email" : "%s", "password":"password","username":"username"}';
Utiliser des constantes

2021-08-26 12:21 UTC, b2p-fred commented on tests/Func/Entity/UserTest.php
> +    private $userPayload = '{"email" : "%s", "password":"password","username":"username"}';
Ou mettre directement dans le code de la fonction utilisatrice ... ce n'est pas utile d'exposer ça dans l'interface de l'objet ;)

2021-08-26 12:27 UTC, shaaxdev requested changes

2021-08-26 12:27 UTC, shaaxdev commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
Il vaut mieux éviter de passer par une variable quand c'est possible, pour des questions de performances et de lisibilité.
Il vaut mieux faire directement `$this->assertInstanceOf(User::class, $this->user->setEmail());`

2021-08-26 12:27 UTC, shaaxdev commented on tests/Unit/Entity/FileTest.php
> +    public function testGetTitre(): void
testGetTitle ;)

2021-08-26 12:27 UTC, shaaxdev commented on tests/Func/Entity/UserTest.php
> +        //dd($responseDecoded);
Il faut enlever les commentaires ;)

2021-08-26 12:27 UTC, shaaxdev commented on tests/Func/Entity/UserTest.php
> +<?php
Dans tes tests API, tu testes le code de la réponse, le format du contenu de la réponse, mais pas le contenu lui-même.
Du coup, si le contenu de la réponse est invalide, les tests passeront quand même.

2021-08-26 13:21 UTC, b2p-ayman commented on tests/Unit/Entity/FileTest.php
> +    public function testGetTitre(): void
Le nommage est basé sur la méthode "getTitre()" de l'entité "File" ;)

2021-08-26 13:27 UTC, b2p-ayman commented on tests/Func/Entity/UserTest.php
> +<?php
Oui, en effet, je vais développer cela dans les prochaines améliorations de l'application

2021-08-26 13:35 UTC, b2p-ayman commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
Si on parle de lisibilité, je trouve qu'il vaut mieux utiliser une variable pour avoir un code plus organisé.

2021-08-27 05:48 UTC, b2p-fred commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
Vos deux avis sont pertinents; par contre je ferai :+1: pour romain ... une variable dans ce cas est complètement inutile et ça reste simple de lire le code quand on écrit ` $this->user->setEmail('ayman@gmail.com');`

2021-08-27 05:48 UTC, b2p-fred commented on tests/Unit/Entity/FileTest.php
> +    public function testGetTitre(): void
Alors la méthode *getTitre* est mal nommée :roll_eyes:

2021-08-27 06:55 UTC, b2p-nidhal approved these changes

2021-08-27 06:55 UTC, b2p-nidhal commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
Je serai plutôt de l'avis d'Aymen, certes dans ce cas particulier l'utilisation d'une variable est redondante car on ne l'utilise qu'une seule fois, mais si dans une itération future on serait amenés à la réutiliser, une variable ( ou une constante globale ) serait un choix plus judicieux à mon avis.

2021-08-27 07:10 UTC, b2p-fred commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
Oui et non :wink: 

Si on n'était pas dans un test, une constante de classe (et pas globale) aurait du sens. Par contr, on est en train d'écrire un test ... alors une simple chaine de caractères va rendre tout le monde content :smile:

2021-08-27 07:30 UTC, b2p-nidhal commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
Oui oui je suis d'accord dans ce cas particulier, je répondais seulement à l'assertion de Romain quant au faite de l'emploie des valeurs brutes serait plus judicieux de point de vue performances et lisibilité. Mais d'un point de vue maintenance de code il vaut mieux utiliser des variables ou des constantes, car en valeurs brutes si une typo se faufile quelque part ça ne serait pas détectable par l'IDE et ça générait une erreur en runtime et on devrait debugger pour résoudre le problème , alors qu'un typo en nom de variable ça générait une erreur en compile-time détectable par l'IDE .

2021-08-27 14:28 UTC, b2p-ayman commented on tests/Unit/Entity/UserTest.php
> +        $response = $this->user->setEmail($value);
J'ai fait une mise à jour (c4c25edde936644d4ca5b9434a4ac815a7e2a73e)

2021-08-27 14:43 UTC, mohierf approved these changes

2021-08-27 14:49 UTC, shaaxdev approved these changes

2021-08-27 14:49 UTC, merged