#24 : Serialization, Operations & Filtres
b2p-ayman/sandbox pull request #25
Opened 2021-08-31 15:35 UTC by b2p-ayman

- Manipuler les groupes de serialization par opérations.
 - La création d'une custom opération.
 - Utiliser les Filtres.

2021-09-01 06:57 UTC, mohierf requested changes
Il faut juste que tu mettes à jour test tests pour que le pourcentage de code coverage ne diminue pas :wink:

2021-09-02 07:01 UTC, b2p-fred requested changes
Same as mohierf :wink:

2021-09-02 07:02 UTC, b2p-fred approved these changes

2021-09-02 07:16 UTC, romainb2p approved these changes

2021-09-02 07:47 UTC, b2p-nidhal approved these changes

2021-09-02 07:47 UTC, merged